using Confluent.Kafka;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Logging;
using VGManager.Adapter.Kafka.Configurations;
using VGManager.Adapter.Kafka.Interfaces;
using VGManager.Adapter.Models;

namespace VGManager.Adapter.Kafka.Extensions;

public static class KafkaConsumerSetupExtension
{
    private const string LogMessageTemplate = "{@KafkaLogMessage}";
    private const string AutoGeneratedGroupIdTemplate = "{0}{1}";

    public static void SetupKafkaConsumer<TMessageType>(
        this IServiceCollection services,
        IConfiguration configuration,
        string kafkaConsumerSectionKey,
        bool autoGenerateGroupId)
        where TMessageType : MessageBase
    {
        var consumerConfig = configuration.GetSection(kafkaConsumerSectionKey)
            .Get<KafkaConsumerConfiguration<TMessageType>>();

        if (autoGenerateGroupId)
        {
            consumerConfig.ConsumerConfig.GroupId = string.Format(
                AutoGeneratedGroupIdTemplate,
                consumerConfig.GroupIdPrefix,
                Guid.NewGuid().ToString()
            );
        }

        services.AddSingleton(serviceProvider =>
        {
            return new ConsumerBuilder<Ignore, TMessageType>(consumerConfig.ConsumerConfig)
            .SetValueDeserializer(new MessageSerializer<TMessageType>())
            .SetLogHandler(LogHandler<TMessageType>(serviceProvider))
            .Build();
        });

        services.AddSingleton(consumerConfig);
        services.AddSingleton<IKafkaConsumerService<TMessageType>, KafkaConsumerService<TMessageType>>();
    }

    private static Action<IConsumer<Ignore, TMessageType>, LogMessage> LogHandler<TMessageType>(IServiceProvider serviceProvider) where TMessageType : MessageBase
    {
        return (consumer, logMessage) =>
        {
            var logger = serviceProvider.GetRequiredService<ILogger<KafkaConsumerService<TMessageType>>>();

            switch (logMessage.Level)
            {
                case SyslogLevel.Emergency:
                case SyslogLevel.Alert:
                case SyslogLevel.Critical:
                    logger.LogCritical(LogMessageTemplate, logMessage);
                    break;
                case SyslogLevel.Error:
                    logger.LogError(LogMessageTemplate, logMessage);
                    break;
                case SyslogLevel.Warning:
                    logger.LogWarning(LogMessageTemplate, logMessage);
                    break;
                case SyslogLevel.Notice:
                case SyslogLevel.Info:
                    logger.LogInformation(LogMessageTemplate, logMessage);
                    break;
                case SyslogLevel.Debug:
                    logger.LogDebug(LogMessageTemplate, logMessage);
                    break;
            }
        };
    }
}
